# Generated by Django 4.1.13 on 2024-03-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='diskSize',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
