# Generated by Django 4.1.13 on 2024-03-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_instance_disksize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('VPCID', models.IntegerField()),
                ('VMID', models.IntegerField()),
                ('state', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
