# Generated by Django 4.1.13 on 2024-03-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_providernetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderNetworkVPCMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VPCID', models.IntegerField()),
                ('subnet', models.CharField(max_length=20)),
            ],
        ),
    ]
