# Generated by Django 4.1.13 on 2024-03-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_providernetworkvpcmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providernetworkvpcmap',
            name='VPCID',
        ),
        migrations.AddField(
            model_name='vpc',
            name='logical_provider_subnet',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
